// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/Celebrities": {
            "post": {
                "description": "Новый celebrity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Celebrities"
                ],
                "summary": "Добавить celebrity",
                "parameters": [
                    {
                        "description": "Celebrity data",
                        "name": "celebrity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Celebrity"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/main.Celebrity"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/Celebrities/All": {
            "get": {
                "description": "Возвращает всех celebrities",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Celebrities"
                ],
                "summary": "Получить всех celebrities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Celebrity"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/Celebrities/{id}": {
            "get": {
                "description": "Возвращает celebrity по id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Celebrities"
                ],
                "summary": "Получить celebrity по id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Celebrity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Celebrity"
                        }
                    },
                    "404": {
                        "description": "Celebrity not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Обновляет celebrity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Celebrities"
                ],
                "summary": "Обновить celebrity",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Celebrity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Celebrity data",
                        "name": "celebrity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Celebrity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Celebrity"
                        }
                    },
                    "404": {
                        "description": "Celebrity not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет celebrity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Celebrities"
                ],
                "summary": "Удалить celebrity",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Celebrity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Celebrity"
                        }
                    },
                    "404": {
                        "description": "Celebrity not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Celebrity": {
            "type": "object",
            "properties": {
                "fullName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nationality": {
                    "type": "string"
                },
                "reqPhotoPath": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Celebrities REST API",
	Description:      "Celebrities через Oracle",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
