FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

COPY . .

RUN dotnet restore gateway.csproj

RUN dotnet publish gateway.csproj -c Release -o out

WORKDIR /app/out

EXPOSE 40000

ENTRYPOINT ["dotnet","gateway.dll"]